### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-html-terminal-and-git-_u9ftI#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-html-terminal-and-git-_u9ftI/) and meets the following criteria:

- [x] A knock-knock joke is displayed when visiting the website
- [x] The code is pushed to GitHub
- [x] The website is hosted on GitHub Pages

**Comment by stuartpearman** [comment]
Hey Rellika,

You've written a lot of HTML here, but it's not really necessary for the assignment. You can just submit text in an HTML file and you'll still get full credit.

Line 7 worries me a bit:

    <meta name="author" content="Ian Yates">

If I'm not mistaken, you would use this tag to tell the browser who the Author is of the page. I can see you wrote some of this code, but be careful what you copy and paste onto your projects. If you copy code carelessly, it could be seen as plagiarism.

The assignment is to put a joke into your HTML file, be sure to re-read the project criteria carefully. Make these changes and resubmit the assignment.

Cheers,

Stuart

**Comment by stuartpearman** [comment]
Oh, and when you submit your project again, just comment on this thread letting me know that you've made changes. That way I'll be able to get feedback to you quickly.

**Comment by kisyular** [comment]
Hello. I have updated the Assignment as required. Sorry about the Meta Tags, I used to think we can use them to credit where you got the meta tags from.

Thank you for pointing this out to me. It really helps a lot. I have kinda been using it a lot to credit the Meta Tags. It will help me rectify some of my personal works.

Kindest Regards

**Comment by stuartpearman** [comment]
Hey Rellika, looking good now! It looks like you changed the name of your repository, keep those the same until we approve your project as the course website relies on a standard naming convention.

Nice work though! :shipit:

**Comment by kisyular** [comment]
@stuartpearman I have renamed the repo back to _MI-449-SS17-740-html-terminal-and-git-_u9ftI_

Thank you

**Comment by kisyular** [comment]
@stuartpearman Is there something else I am missing in my project. Tells me there are changes requested

**Comment by stuartpearman** [comment]
Nope, you're good, just a bug with the name changes. I'll give you another shipit squirrel :shipit:

Let me know if it still doesn't work.
